"""Validate a final topic run and generate manuscript-facing metadata."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from topic_classification.provenance import (
    validate_topic_group_outputs,
    validate_topic_table_outputs,
    validate_topic_visualization_outputs,
)
from topic_classification.scripts._impl.reproducibility import (
    command_output,
    write_run_manifest,
)


DEFAULT_TOPIC_DIR = Path(
    "/home/akroon/data/1t_storage/RESPOND-victims-of-corruption/"
    "topic_classification/bertopic_political_corruption_source_filtered_200_min10"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate final topic outputs and write manuscript metadata."
    )
    parser.add_argument("--bertopic-dir", type=Path, default=DEFAULT_TOPIC_DIR)
    return parser.parse_args()


def comma(value: int) -> str:
    return f"{int(value):,}"


def write_manuscript_values(path: Path, values: dict[str, str]) -> None:
    lines = [
        "% Generated by topic_classification/scripts/_impl/finalize_topic_outputs.py.",
        "% Do not edit these values manually.",
    ]
    lines.extend(
        rf"\providecommand{{\{name}}}{{{value}}}" for name, value in values.items()
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    bertopic_dir = args.bertopic_dir.resolve()
    provenance = validate_topic_group_outputs(bertopic_dir)
    visualization_provenance = validate_topic_visualization_outputs(bertopic_dir)
    table_provenance = validate_topic_table_outputs(bertopic_dir)

    import pandas as pd

    topic_info_path = bertopic_dir / "topic_info.csv"
    documents_path = bertopic_dir / "document_topics.csv.gz"
    labels_path = bertopic_dir / "topic_labels_llm.csv"
    groups_path = bertopic_dir / "topic_groups_llm.csv"
    summary_table = (
        bertopic_dir
        / "inspection_tables"
        / "latex"
        / "table_topic_higher_order_summary.tex"
    )
    inventory_table = (
        bertopic_dir
        / "inspection_tables"
        / "latex"
        / "table_all_topics_llm_higher_order_topics.tex"
    )
    required_paths = [
        topic_info_path,
        documents_path,
        labels_path,
        groups_path,
        summary_table,
        inventory_table,
    ]
    missing = [path for path in required_paths if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Final topic output is incomplete: " + ", ".join(str(path) for path in missing)
        )

    topic_info = pd.read_csv(topic_info_path)
    documents = pd.read_csv(documents_path, usecols=lambda col: col in {"topic"})
    labels = pd.read_csv(labels_path)
    groups = pd.read_csv(groups_path)

    fine_topic_ids = set(topic_info.loc[topic_info["Topic"].ne(-1), "Topic"].astype(int))
    label_topic_ids = set(labels["Topic"].dropna().astype(int))
    group_topic_ids = set(groups["Topic"].dropna().astype(int))
    if label_topic_ids != fine_topic_ids:
        raise ValueError(
            "GPT topic labels do not cover exactly the current non-outlier topics."
        )
    if group_topic_ids != fine_topic_ids or groups["Topic"].duplicated().any():
        raise ValueError(
            "Higher-order assignments must cover every non-outlier topic exactly once."
        )
    if groups["topic_group_id"].fillna("").astype(str).str.strip().eq("").any():
        raise ValueError("At least one fine-grained topic lacks a higher-order group.")

    sample_n = int(len(documents))
    inlier_n = int(documents["topic"].ne(-1).sum())
    outlier_n = sample_n - inlier_n
    fine_topic_n = len(fine_topic_ids)
    observed_group_n = int(groups["topic_group_id"].nunique())
    configured_groups = (
        provenance["manifest"].get("extra", {}).get("higher_order_topics") or []
    )
    configured_group_n = len(configured_groups)
    if configured_group_n != 6:
        raise ValueError(
            f"Expected six documented higher-order groups, found {configured_group_n}."
        )

    upstream = provenance["upstream_classifier"]
    values = {
        "TopicModelSampleN": comma(sample_n),
        "TopicModelFineTopicN": comma(fine_topic_n),
        "TopicModelInlierN": comma(inlier_n),
        "TopicModelOutlierN": comma(outlier_n),
        "TopicModelInlierShare": f"{100 * inlier_n / sample_n:.1f}",
        "TopicModelOutlierShare": f"{100 * outlier_n / sample_n:.1f}",
        "TopicModelConfiguredGroupN": comma(configured_group_n),
        "TopicModelObservedGroupN": comma(observed_group_n),
        "TopicModelClassifierN": comma(
            int(upstream["political_corruption_articles"])
        ),
        "TopicModelClassifierThreshold": f"{float(upstream['threshold']):.2f}",
    }
    latex_dir = summary_table.parent
    values_path = latex_dir / "topic_model_manuscript_values.tex"
    write_manuscript_values(values_path, values)

    summary = {
        "built_at_utc": datetime.now(timezone.utc).isoformat(),
        "generator_git_commit": command_output(
            ["git", "rev-parse", "HEAD"], cwd=PROJECT_ROOT
        ),
        "classifier": upstream,
        "sample_articles": sample_n,
        "fine_grained_non_outlier_topics": fine_topic_n,
        "inlier_articles": inlier_n,
        "outlier_articles": outlier_n,
        "inlier_share": inlier_n / sample_n,
        "configured_higher_order_groups": configured_group_n,
        "observed_higher_order_groups": observed_group_n,
    }
    summary_path = bertopic_dir / "topic_model_build_summary.json"
    summary_path.write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    latest_path = bertopic_dir / "00_LATEST_TOPIC_MODEL_BUILD.txt"
    latest_lines = [
        "LATEST RESPOND TOPIC-MODEL BUILD",
        "=================================",
        "",
        f"Built (UTC): {summary['built_at_utc']}",
        f"Generator Git commit: {summary['generator_git_commit']}",
        f"Classifier Git commit: {upstream.get('classifier_git_commit')}",
        f"Classifier manifest SHA-256: {upstream.get('classifier_manifest_sha256')}",
        f"Classifier threshold: {float(upstream['threshold']):.2f}",
        f"Final political-corruption corpus: {int(upstream['political_corruption_articles']):,}",
        f"Topic-model sample: {sample_n:,}",
        f"Fine-grained non-outlier topics: {fine_topic_n:,}",
        f"Inlier articles: {inlier_n:,} ({100 * inlier_n / sample_n:.1f}%)",
        f"Outlier articles: {outlier_n:,} ({100 * outlier_n / sample_n:.1f}%)",
        f"Configured higher-order groups: {configured_group_n}",
        "",
        "CANONICAL RESEARCH DRIVE FILES",
        "--------------------------------",
        "output/tables/topic_models/topic_model_manuscript_values.tex",
        "output/tables/topic_models/table_topic_higher_order_summary.tex",
        "output/topic_model_output_manifest.json",
        "output/00_LATEST_TOPIC_MODEL_BUILD.txt",
        "",
        "The full fine-grained inventory is retained in the reproducibility archive,",
        "not inserted into the manuscript by default.",
        "",
    ]
    latest_path.write_text("\n".join(latest_lines), encoding="utf-8")

    write_run_manifest(
        bertopic_dir,
        script_name=Path(__file__).name,
        args=args,
        inputs={
            "topic_group_manifest": provenance["manifest_path"],
            "topic_info": topic_info_path,
            "document_topics": documents_path,
            "topic_labels": labels_path,
            "topic_groups": groups_path,
            "higher_order_summary_table": summary_table,
            "fine_grained_inventory_table": inventory_table,
            "visualizations_manifest": visualization_provenance["manifest_path"],
            "topic_tables_manifest": table_provenance["manifest_path"],
        },
        outputs={
            "manuscript_values": values_path,
            "build_summary": summary_path,
            "latest_index": latest_path,
        },
        extra=summary,
        manifest_name="topic_model_output_manifest.json",
    )

    print(f"Validated final topic run: {bertopic_dir}", flush=True)
    print(
        f"Sample N={sample_n:,}; fine-grained topics={fine_topic_n:,}; "
        f"outliers={outlier_n:,}",
        flush=True,
    )
    print(f"Saved manuscript values: {values_path}", flush=True)
    print(f"Saved latest-build index: {latest_path}", flush=True)


if __name__ == "__main__":
    main()
